<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$finder = (new Finder())
    // ->in(__DIR__)
    ->in([
        __DIR__ . '/app',
        __DIR__ . '/bootstrap',
        __DIR__ . '/config',
        __DIR__ . '/database',
        __DIR__ . '/public',
        __DIR__ . '/resources',
        __DIR__ . '/routes',
        __DIR__ . '/tests',
    ])
    ->name('*.php')
    ->notName('*.blade.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true)
    ->exclude('var');

return (new Config())
    ->setFinder($finder)
    // ->setRiskyAllowed(false)
    ->setRiskyAllowed(true)
    ->setUsingCache(true)
    ->setIndent("    ")
    // ->setIndent("\t")
    ->setLineEnding("\n")
    ->setRules([
        '@PSR12'                                           => true,
        '@Symfony'                                         => true,
        'align_multiline_comment'                          => false,
        'array_indentation'                                => true,
        'array_syntax'                                     => ['syntax' => 'short'],
        'binary_operator_spaces'                           => ['operators' => ['=>' => 'align', '=' => 'align']],
        'blank_line_after_opening_tag'                     => false,
        'blank_line_before_statement'                      => true,
        'blank_lines_before_namespace'                     => true,
        'cast_spaces'                                      => true,
        'class_attributes_separation'                      => ['elements' => ['method' => 'one']],
        'combine_consecutive_issets'                       => false,
        'combine_consecutive_unsets'                       => false,
        'combine_nested_dirname'                           => false,
        'comment_to_phpdoc'                                => false,
        'compact_nullable_typehint'                        => false,
        'concat_space'                                     => ['spacing' => 'one'],
        'constant_case'                                    => ['case' => 'lower'],
        'date_time_immutable'                              => false,
        'declare_equal_normalize'                          => true,
        'declare_strict_types'                             => false,
        'dir_constant'                                     => false,
        'doctrine_annotation_array_assignment'             => false,
        'doctrine_annotation_braces'                       => false,
        'doctrine_annotation_indentation'                  => ['ignored_tags' => [], 'indent_mixed_lines' => true],
        'doctrine_annotation_spaces'                       => ['after_argument_assignments' => false, 'after_array_assignments_colon' => false, 'after_array_assignments_equals' => false],
        'elseif'                                           => false,
        'encoding'                                         => true,
        'include'                                          => true,
        'indentation_type'                                 => true,
        'lowercase_cast'                                   => true,
        'multiline_whitespace_before_semicolons'           => true,
        'no_empty_comment' => false,
        'no_extra_blank_lines'                             => ['tokens' => ['curly_brace_block', 'extra', 'throw', 'use']],
        'no_multiline_whitespace_around_double_arrow'      => true,
        'no_singleline_whitespace_before_semicolons'       => true,
        'no_spaces_around_offset'                          => true,
        'no_unused_imports'                                => false,
        'no_useless_else'                                  => true,
        'no_useless_return'                                => true,
        'no_whitespace_before_comma_in_array'              => true,
        'no_whitespace_in_blank_line'                      => true,
        'object_operator_without_whitespace'               => true,
        'ordered_imports'                                  => true,
        'single_line_comment_style'                        => ['comment_types' => ['hash']],
        'single_quote'                                     => false,
        'space_after_semicolon'                            => true,
        'ternary_operator_spaces'                          => true,
        'ternary_to_null_coalescing'                       => true,
        'trim_array_spaces'                                => true,
        'type_declaration_spaces'                          => true,
        'unary_operator_spaces'                            => true,
        'whitespace_after_comma_in_array'                  => true,
        // 'class_definition' => array('singleLine' => true),
        // 'control structure braces'                         => true,
        // 'control structure continuation position'          => true,
        // 'curly braces position'                            => true,
        // 'declare parentheses'                              => true,
        // 'increment_style' => true,
        // 'native_function_casing' => true,
        // 'new_with_braces' => true,
        // 'no extra blank lines'                             => true,
        // 'no multiple statements per line'                  => true,
        // 'no_blank_lines_after_class_opening' => true,
        // 'no_blank_lines_after_phpdoc' => true,
        // 'no_empty_comment' => true,
        // 'no_empty_phpdoc' => true,
        // 'no_empty_statement' => true,
        // 'no_leading_import_slash' => true,
        // 'no_leading_namespace_whitespace' => true,
        // 'no_mixed_echo_print' => array('use' => 'echo'),
        // 'no_short_bool_cast' => true,
        // 'no_singleline_whitespace_before_semicolons' => true,
        // 'no_trailing_comma_in_list_call' => true,
        // 'no_trailing_comma_in_singleline_array' => true,
        // 'no_unneeded_control_parentheses' => true,
        // 'no_unused_imports'                                => true,
        // 'normalize_index_brace' => true,
        // 'php_unit_fqcn_annotation' => true,
        // 'phpdoc_align' => true,
        // 'phpdoc_annotation_without_dot' => true,
        // 'phpdoc_indent' => true,
        // 'phpdoc_inline_tag' => true,
        // 'phpdoc_no_access' => true,
        // 'phpdoc_no_alias_tag' => true,
        // 'phpdoc_no_empty_return' => true,
        // 'phpdoc_no_package' => true,
        // 'phpdoc_no_useless_inheritdoc' => true,
        // 'phpdoc_return_self_reference' => true,
        // 'phpdoc_scalar' => true,
        // 'phpdoc_separation' => true,
        // 'phpdoc_single_line_var_spacing' => true,
        // 'phpdoc_summary' => true,
        // 'phpdoc_to_comment' => true,
        // 'phpdoc_trim' => true,
        // 'phpdoc_types' => true,
        // 'phpdoc_var_without_name' => true,
        // 'return_type_declaration' => true,
        // 'self_accessor' => true,
        // 'short_scalar_cast' => true,
        // 'single space around construct'                    => true,
        // 'single_blank_line_at_eof' => false
        // 'single_blank_line_before_namespace' => true,
        // 'single_class_element_per_statement' => true,
        // 'standardize_not_equals' => true,
        // 'statement indentation'                            => true,
        // 'trailing_comma_in_multiline' => ['elements' => ['arrays']],
    ]);
